version = 1
SPDX-PackageName = "SAP-docs/btp-application-autoscaler"
SPDX-PackageSupplier = "Sylvia Hoerdt (sylvia.hoerdt@sap.com)"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/btp-application-autoscaler"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and SAP-docs/btp-application-autoscaler contributors"
SPDX-License-Identifier = "CC-BY-4.0"
